### ISSUE TITLE
Passing Params from the SSRS report enumerations dropdown boxes

### ISSUE THREAD

**Issue by RickZler** [armanio123/ReportViewerForMvc#2]
Hi:

I just started my adventure of trying to get SSRS reports to serve up in a ASP.NET MVC 4 environment.
We use HTML Helpers like @HtmlModelFor  to our strongly typed LINQ sequences to render our views
with the collections from the controller classes. Our reports have many user selection criteria that the user
chooses from drop down boxes in the SSRS report itself. What would be your suggestion for setting up
a process (maybe a factory collection method) besides using a query string to send the params from
the report to the view. In other words the user needs to have the ability to send the selections of dropdown boxes from the MVC view model back to the report and have the dataset return the output of the related selections from the newly flattened query to the view via the report. I didn't see any examples of actual passing params to report and having the report reflect the collection information on the report.
Your solution seems like a great solution so I'll probably take the time to struggle with it and try to get it right. Do you monitor this section for any problems I might have deploying your solution. I really try to solve these things myself but every once in a while you have to reach out for help. Thanks for a great looking alternative. Can't wait to give it a shot.

**Comment by armanio123** [comment]
Hi, I'm not sure if I'm understanding the question but there's an example of how to set report parameters (either local or server) on the [Examples controller](https://github.com/armanio123/ReportViewerForMvc/blob/41ff053b5fc5663542c5139366d3258de81edec3/ReportViewerForMvc.Example/Controllers/ExamplesController.cs#L39). Check it out and let me know if that is what you were looking for.

In regards to monitoring problems. I'll be taking a look every now and then. Feel free to send any PRs and issues. I'll do my best to address them. Also you mighty want to take a look at a bunch of [issues](http://reportviewerformvc.codeplex.com/workitem/list/basic) from before moving to GitHub that I never work through. I'll dedicate a little bit to catch up.

Glad to help.

**Comment by RickZler** [comment]
Hi Armando:
Thanks for the reply. I wasn’t sure if it was O.K. to reply to this in an email but if it is a problem I ‘ll just copy and paste this discourse back into the forum on the MVCReportViewer page.
I just wanted to know if the software will accept parameters like
A start date and end date for parameters that a user will enter on
the report. Like for instance search for invoices between 02/19/2017 to 03/19/2017 where the user types those dates into a date picker or text box on the report. So the ASP.NET view would need to pass this  to a controller and visa versa. So the date field would go from the report itself and get passed into a MVC controller . I just need to know if your package will facilitate such
an action.

Thanks
       Rich
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by armanio123** [comment]
If your report already contains the dates filter, that's all you need. Just configure the ReportViewer control with your report and this project will take care of rendering and postbacks.

If you have the filter external to the report, then you'll need to pass the filter selections on the parameters (like the examples). Once you change those filters, you'll need to re-render the report manually. I don't suggest doing that unless you have a specific need for it.

This library does not provide with a way for extracting data from the report only for rendering. If you like to do that, you'll need to do some JavaScript.

Behind scenes what's happening is that the ReportViewer data is being copied to an ASP.NET WebForm, for allowing the Microsoft's ReportViewer to provide with all the features that it already has. That includes rendering and refreshing filters.

**Comment by armanio123** [comment]
Does my answer helped clearing your questions?

**Comment by RickZler** [comment]
Yes Sir:

But I’m just now starting this long journey and
haven’t really started coding anything as of yet.
I’m sure I’ll have more questions after spending
quite some time trying to solve them myself.
Hopefully I’ll be wrong but incorporating web form type functionality into an MVC application just seems like a head ache 😖

Sent from my iPhone

On Oct 11, 2017, at 2:03 PM, Armando Aguirre <notifications@github.com<mailto:notifications@github.com>> wrote:


Does my answer helped clearing your questions?
