### ISSUE TITLE
How I could display a waiting message while loading the report.

### ISSUE THREAD

**Issue by jarlopez12** [armanio123/ReportViewerForMvc#9]
Hi,

The blank box could make you think that a mistake occurred.

![image](https://user-images.githubusercontent.com/32877914/32065200-e0bd08c6-ba30-11e7-9968-aa7f5e44bde6.png)

Thaks you.

**Comment by NessfertIndia** [comment]
Hi jarlopez12 
I am alos working on same issue  [ You can see history here [https://github.com/armanio123/ReportViewerForMvc/issues/3](https://github.com/armanio123/ReportViewerForMvc/issues/3)  Please share here if any progress or work arounds you found

**Comment by armanio123** [comment]
As @NessfertIndia mentioned, he has proposed to add an event handler for knowing when a report has finished loading. That way you could add some kind of loading message.

We'll follow up this on the other post: [Support to Capture the event for Rendering completion](https://github.com/armanio123/ReportViewerForMvc/issues/3).
